# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        container_name: trucks-php
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '80:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1,
            APP_SERVICE: '${APP_SERVICE}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        container_name: trucks-mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'local'
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'local'
            MYSQL_PASSWORD: 'local'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]

    phpmyadmin:
        container_name: trucks-pma
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOSTS: mysql
        ports:
            - 90:80
        depends_on:
            - mysql
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local